// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZvOKcEPynCy851cwXN7oq7Wg5UZMxkQc',
    appId: '1:640290034298:web:2ac901f0f389af6c0e61c3',
    messagingSenderId: '640290034298',
    projectId: 'name-checker-app',
    authDomain: 'name-checker-app.firebaseapp.com',
    storageBucket: 'name-checker-app.firebasestorage.app',
    measurementId: 'G-D3S05EG9FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTE3q-fxlcrzP2kDAKeoXC1EY--IkEnug',
    appId: '1:640290034298:android:7e4d957b8e6cc9f60e61c3',
    messagingSenderId: '640290034298',
    projectId: 'name-checker-app',
    storageBucket: 'name-checker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhErdx3YXyL5xsEVnnZWO411aKgi8lbdY',
    appId: '1:640290034298:ios:15389349e4f71c4b0e61c3',
    messagingSenderId: '640290034298',
    projectId: 'name-checker-app',
    storageBucket: 'name-checker-app.firebasestorage.app',
    iosBundleId: 'com.example.nameCheckerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhErdx3YXyL5xsEVnnZWO411aKgi8lbdY',
    appId: '1:640290034298:ios:15389349e4f71c4b0e61c3',
    messagingSenderId: '640290034298',
    projectId: 'name-checker-app',
    storageBucket: 'name-checker-app.firebasestorage.app',
    iosBundleId: 'com.example.nameCheckerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZvOKcEPynCy851cwXN7oq7Wg5UZMxkQc',
    appId: '1:640290034298:web:1f2756b06e2aa1b70e61c3',
    messagingSenderId: '640290034298',
    projectId: 'name-checker-app',
    authDomain: 'name-checker-app.firebaseapp.com',
    storageBucket: 'name-checker-app.firebasestorage.app',
    measurementId: 'G-PC6ZYH2S4V',
  );
}
